pygments: false
lsi: false
future: false
plugins: ./_plugins
permalink: /:title/
paginate: 5
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'config', 'vendor']
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']
url: https://www.docsoc.co.uk/
baseurl:
name: Imperial DoCSoc
description: Imperial College Computing Society
author: DoCSoc Committee
email: docsoc@imperial.ac.uk
twitter: icdocsoc
gravatar_url: https://secure.gravatar.com/avatar

excerpt_length: 250

authors:
  pete:
    name: Pete Hamilton
    gravatar: /77faa2710fecfe4571525201a729ba25
    twitter: peterejhamilton
    email: peter.hamilton10@imperial.ac.uk
    github: petehamilton
